### ISSUE TITLE
How to disable service worker in dev mode?

### ISSUE THREAD

**Issue by TimPietrusky** [PolymerX-skeleton-templates/default#62]
I created my project using the `polymerx create default` skeleton and now I always get two errors saying that sw.js doesn't exist. 

How can I disable this? I mean without removing the code from index.html and src/index.js? 

Shouldn't there be any conditions that if this is a dev-mode project, we don't put the service worker code into index.html and into the bundle?

**Comment by LasaleFamine** [comment]
Hi @TimPietrusky thank you for reporting this one.

Firstly you just catch a problem: the script for loading the SW on the index.html is redundant and must be removed.

By the way we can simply switch the `console.error` to a `console.warning` or simply `.info` when the `sw.js` is not found, so you would'n have that annoying error. Also, we can programmatically import the `sw-loader.js` in the `index.js` but I think this is not really needed.

I'm going to fix these two problems for now. Thank you!

**Comment by TimPietrusky** [comment]
@LasaleFamine Can you please point to the commit that fixes the issue? So that I can do the fix myself?
